### ISSUE TITLE
any exmaples?

### ISSUE THREAD

**Issue by lucasjinreal** [AssemblyAI-Examples/MinImagen#3]
any exmaples?

**Comment by oconnoob** [comment]
@jinfagang We trained for a bit using conceptual captions, but given that the implementation is designed for educational purposes and strips off many of the amazing improvements made in Diffusion Models over the last couple of years, training is slow and results are not SOTA. If you'd like, I may be able to upload the checkpoint if you want something to start a training from.

Otherwise, can I suggest looking into Stable Diffusion? It open source and they have released weights since you left your comment - we have a guide on [how to run stable diffusion](https://www.assemblyai.com/blog/how-to-run-stable-diffusion-locally-to-generate-images/) which will get you up-and-running in 5-10 minutes!
![image_0](https://user-images.githubusercontent.com/46252299/186694895-54cc14a1-2f49-48b6-ae91-83572cb6b3c6.png)
